booking_homepage:
    path:     /
    defaults: { _controller: BookingBundle:Default:index }

booking_get_by_room:
    path:     /room/{email}
    defaults: { _controller: BookingBundle:Default:getByRoom, email: null }

booking_detail_get_by_room:
    path:     /room/{email}/detail
    defaults: { _controller: BookingBundle:Default:getDetailByRoom, email: null }

booking_is_room_available:
    path:     /room/{email}/is_available
    defaults: { _controller: BookingBundle:Default:isRoomAvailable, email: null }

booking_count_occupied_room:
    path:     /rooms/occupied_count
    defaults: { _controller: BookingBundle:Default:getOccupiedRoomCount }