booking_get_by_room:
    path:     /room/{email}
    defaults: { _controller: BookingBundle:Default:getDetailByRoom, email: null }

booking_count_occupied_room:
    path:     /rooms/occupied_count
    defaults: { _controller: BookingBundle:Default:getOccupiedRoomCount }